spring.application.name=learn-fhir

spring.datasource.url=jdbc:postgresql://localhost:5432/simple_FHIR_app
spring.datasource.username=postgres
spring.datasource.password=2457

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true